name: Build and Release Summit

on:
  push:
    branches:
      - summit-main

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache npm dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.npm
          node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: Setup Node.js environment
      uses: actions/setup-node@v4

    - name: Install jq
      run: sudo apt-get install jq

    - name: Install dependencies
      run: |
        npm install -g webpack @types/jest jest typescript webpack-cli npm-run-all
        npm ci
      
    - name: Build Summit
      run: |
        mkdir -p ./dist
        npx webpack --config webpack.config.js --mode production
      working-directory: ${{ github.workspace }}

    - name: Zip summit
      run: zip -r summit.zip dist/*

    - name: Upload web extension as artifact
      if: github.ref == 'refs/heads/dev'
      uses: actions/upload-artifact@v2
      with:
        name: Summit
        path: ./summit.zip

    - name: Create Release
      id: create_release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: ${{ steps.get_version.outputs.VERSION }}
        release_name: Release ${{ steps.get_version.outputs.VERSION }}
        files: |
          ./summit.zip
        prerelease: false
        draft: false
    
    # - name: Publish
    #   run:  |
    #     cd npm
    #     npm publish
    #   env:
    #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
    # - name: Publish to GitHub Packages
    #   run:  |
    #     cd npm
    #     npm publish
    #   env:
    #     NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
